### ISSUE TITLE
Can't load all results when field is empty

### ISSUE THREAD

**Issue by JoshuaTyree** [jamalneufeld/ghostHunter#18]
Theoretically when the search field is emptied, it should return all results.

Calling clear() on the search field does not produce the intended results.

Before interaction
<img width="2042" alt="screenshot 2016-01-12 23 45 21" src="https://cloud.githubusercontent.com/assets/9021372/12286073/a64080a8-b986-11e5-9052-f0c21db0c237.png">

Entered field and pressed backspace
<img width="1468" alt="screenshot 2016-01-12 23 45 32" src="https://cloud.githubusercontent.com/assets/9021372/12286072/a62bb146-b986-11e5-85a3-31ad9fa74ecf.png">

**Comment by Windyo** [comment]
This is actually because Lunr works by matching stems. Clearing the field provides no data to match, so lunr fails to match results.

This aside, I'de like to hear someone's thoughts on this.

Theoretically it would be possible to check if a query was made prior to clearing the field, in which case clearing the field could return a full list of posts.
However, this could be problematic for users who use the onKeyUp option. How do you dismiss results  if clearing the field displays a full list of posts ?
For users using a "submit" button, this could be circumvented by a "clear" button", but from a UX point of view this is far from perfect.

As is, I don't think implementing this into GhostHunter is in the best interest of the end users.

**Comment by cjsheets** [comment]
Since I just went through an implementation I'll offer my thoughts.

Personally, I think displaying all results for an empty query is not a function for the search script, but rather a UI/design choice. Without much effort you could implement an interface that returns to an index of all posts when the search field is empty. Other implementations wouldn't want this behavior (for example, removing a term from Google shouldn't result in the entire web being returned).

Either design choice is valid and I don't meant to suggest  JoshuaTyree is wrong. If Lunr made it trivial to implement as an option I wouldn't be opposed, but since it's on the design/UI end and not the search end I'd vote to leave it up to the developer to work out what to do with an empty box.

**Comment by Windyo** [comment]
I agree with you here @cjsheets.

Using CSS and the ghost GET helper, it is should be possible to display a list of posts if the search field was is empty. Implementing it as a function of Ghosthunter would also require putting in place checks against situations like the one described above.

While the question and functional need are valid, this should be put in place at the theme level, not the search engine level.
Labeled as Wontfix.
