### ISSUE TITLE
Search System not working/Expanding Search System?

### ISSUE THREAD

**Issue by ItsMohammad** [jamalneufeld/ghostHunter#28]
Hello, I own a site called IAskMuslim.com, and we have been having problems with your search system. The  first problem is that when someone searches something on the site itself many of the public discussions never show up. Any idea how I can make so for example if someone types "Muslim" it would show all of the posts with the word Muslim in it? Another thing, I was going to ask you guys is do you have any plans on advancing the Search System itself. 

To work something like this. 
https://vanillaforums.org/search

**Comment by Windyo** [comment]
Hi there,
going to your site shows no search bar.

The app.min.js you are using contains the ghosthunter logic, but you are using a deprecated version. If you want to stick with RSS use dreampiggy's fork- otherwise the new version uses the API.

The post limitation you speak about is actually a known limitation of the rss query in ghost which only returns 15 posts. This has beeen solved with the new version.

**Comment by ItsMohammad** [comment]
Okay, I will give this link to the dev of the theme so he can update it thanks!

**Comment by ItsMohammad** [comment]
Hello, could you update my search-form.hbs for me since I don't understand how to do it?
http://pastebin.com/AT2ZKWNy

PS:
I turned on Public API since you said I would need that.

Thanks for your help!

**Comment by ItsMohammad** [comment]
And yes I'm running the latest software for Ghost.

**Comment by ItsMohammad** [comment]
Repost:

Hello, could you update my search-form.hbs for me since I don't understand how to do it?
http://pastebin.com/AT2ZKWNy

PS:
I turned on Public API since you said I would need that.
And yes I'm running the latest software for Ghost.

Thanks for your help!

**Comment by Windyo** [comment]
I was going to look at it, and then you did your entitled "repost" thing and I decided not to.

Check with your theme developer.
