### ISSUE TITLE
It does not work properly

### ISSUE THREAD

**Issue by ubuntutest** [jamalneufeld/ghostHunter#50]
I've always used a very old version of ghosthunter, about 185 lines of code, I've never had any kind of problem. I tried to update, the latest version is about 3500 lines of code, unfortunately I must say that it works very badly. I do not understand why. It does not sort the articles according to the search key, often in the search result there are articles completely unrelated to the searched word, or simply not find them all. I'm forced to go back to the previous version, old for several months, or years, fortunately I had saved it :)
I wanted to warn you of this problem, I'm probably wrong?

**Comment by fbennett** [comment]
Sounds like we should make exact-match searching the default.

**Comment by fbennett** [comment]
There isn't much additional code in this version---`lunr.js` was written on a single line previously. So there is no call to be alarmed about that. The search results you are seeing are due to fuzzy matching. I was responsible for the pull request that brought us to this version, so I will adjust the code to make exact matching the default, with fuzzy search as an option. Look for an update in a week or two.

**Comment by ubuntutest** [comment]
Thanks for the reply and for the explanation. Actually in my case I need the exact result. Maybe it's not like that for other people.
Regarding the lines of code I was talking about jquery.ghosthunter.js, it is not minified on a line of code, there is a difference of 3200 lines. If you want, I can send it to you

**Comment by Windyo** [comment]
^ The old version is probable the RSS one, which was a bit more condensed before we added static pages support for example.

I'm going to close this one as it circles back to matching type which is covered in #49. Any further issue regarding results due to matching types should be forwarded there.
