### ISSUE TITLE
Support other languages 

### ISSUE THREAD

**Issue by Adidi** [jamalneufeld/ghostHunter#52]
Does ghostHunter support other languages then english cause when I write post with an Hebrew title and search for the excat title - I get no results

Any Idea? is it something in the configurations ?

**Comment by fbennett** [comment]
ghostHunter uses `lunr.js` for index/search. It supports [several non-English languages](https://lunrjs.com/guides/language_support.html), but Hebrew is not among them, unfortunately.

**Comment by Windyo** [comment]
GH uses Lunr to search.
Lunr is notoriously incompatible with a lot of other languages - there was one specific instance of ghosthunter where someone made an entire fork just to support Chinese for example.

The lunr issue tracker makes it seem that this won't be supported:
https://github.com/olivernn/lunr.js/issues/216

A possible workaround for you would be to implement what is suggested in that issue and bypass the lunr pipeline and stemming completely.

I'll close this because we unfortunately have no way of enabling this feature
