### ISSUE TITLE
Origin is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by 2blane** [jamalneufeld/ghostHunter#54]
I am trying to host my ghost blog on both www.example.com and example.com. I set the site url of the blog to be example.com. If I try searching on example.com everything works as expected. If however, I try searching on www.example.com I get errors and search results are not returned. I'm guessing this has to do with CORS? Is there CORS somewhere in this code or is this a LocalStorage issue? Seems like you can't call the API methods from anything but the exact site url that you specify. Here is the error I get when trying to search:

`https://example.com/blog/ghost/api/v0.1/posts/?limit=all&include=tags&formats=plaintext*client_id=ghost-frontend&client_secret=abcdef123
`

`Failed to load resource: Origin https://www.example.com is not allowed by Access-Control-Allow-Origin.
`

**Comment by Windyo** [comment]
Yeah this is the API itself being annoying with domains.
You’ll need to follow this https://api.ghost.org/docs/ajax-calls-from-an-external-website

Otherwise contact the Ghost team directly over their slack, they may be able to help.

https://slack.ghost.org/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by 2blane** [comment]
Thanks so much! This was the problem! Just add in both https://www.example.com and https://example.com as a client_trusted_domain in your database for the ghost client which is ghost-frontend and everything will work as expected.
