### ISSUE TITLE
[Question] Does this search body as well as titles?

### ISSUE THREAD

**Issue by ErikAGriffin** [jamalneufeld/ghostHunter#55]
Looking at many ghost installations, their search only runs through the blog titles.  While based on the screenshot it would _appear_ that this does indeed also search post content, I wanted to make sure before I dived in to installing this.

Sorry if this is written clearly somewhere, scanning through the content I saw no mention of what exactly is indexed

**Comment by TaoK** [comment]
This does indeed search post content. I don't know how comprehensive a job it does (I haven't looked at the detail of the API responses on which the indexing is done) but my spot-checking today definitely showed contents being indexed properly pretty far down the page.

That said, the theme within which the ghosthunter search was included/embedded, "polar" as of a couple months ago, had an OLD version of ghosthunter, which in my case at least did not work properly. I couldn't easily figure out what version of ghosthunter it was, because it was minified with comment stripping, but upgrading to 0.5 fixed it for me.

**Comment by Windyo** [comment]
It does.
It gets the full post content via the API and indexes that.

the old version of ghosthunter (like REALLY old) used RSS, and that didn't search contents.
All later versions using the API do.
