### ISSUE TITLE
`onPageLoad:true` creates a DDOS effect

### ISSUE THREAD

**Issue by ErisDS** [jamalneufeld/ghostHunter#66]
GhostHunter is an awesome theme plugin, it's being used widely by Ghost themes everywhere.

As we see it being used with bigger and busier publications, we're seeing that the `onPageLoad:true` default setting creates a DDOS effect, as every page load triggers a huge request for data.

We're seeing this cause all kinds of problems, including blogs becoming very very slow and even stop working all together. 

We're looking at a range of solutions such as removing or strongly rate limiting the posts endpoint when `limit=all` is set. This would cause problems for ghostHunter, so I wanted to drop by and 

1. suggest switching `onPageLoad:true` back to false by default 
2. ask if there are any obvious API changes we could make to help GhostHunter be more efficient

**Comment by Windyo** [comment]
Hey Hannah !

Thanks for all the work you guys are doing over at ghost.

I haven't been as active on github as I would like lately. I need to fix a couple of issues on 0.5.0 anyway, so i'll do a minor version change and set `onPageLoad` to False - probably end of next week.

Regarding making Ghosthunter more efficient, the obvious change would be to put it server-side, cache the result of the query, and stop querying everything page by page. I see someone has made a server-side implementation of GH at https://github.com/HexRweb/GhostHunter-server, though I haven't tested it. As for me, I am simply not good a coder enough to carry out that change.

API-Wise apart making sure we can query the minimum amount of information we need on both fields, tags and authors, I am not really sure what could be optimized. Maybe Ghost could store an index of some post parameters, like `Title`, and return a Json upon query of a specific endpoint? Would be more efficient than us querying just the title, and then building the index out of it... for full post contents I expect we should always query it anyway, but for bigger blogs that open should be set to FALSE anyway. What could be interesting is allowing a toggle on the frontend to say "search post content" rather than the backend parameter.
Once again though, not good enough to implement that and document it in a usable format for the users.

Happy to discuss if there's other small changes I can do to make you guys lives easier.
Cheers

**Comment by max-nova** [comment]
I found that the biggest issue here was the 'plaintext' key that loads the full text of every post.  I really just wanted title / tag search, so I pulled out the plaintext lines and it works great!  Demo at https://books.max-nova.com

**Comment by Windyo** [comment]
Hey @ErisDS, sorry for taking so long.
So I pushed a minor update today to close this.

Changes:
- `onpageload` default to `false`
- new param `includebodysearch`, default `false`

if the new param is left `false`, the API call explicitly asks for no formats - meaning the return doesn't even include HTML.
if `true`, it includes plaintext as before.

I hope this'll lower load on your servers. I'll close this for now as it's been stale for a while - let me know if there's anything else.

**Comment by Windyo** [comment]
@max-nova also, just for my curiosity : did you simply remove the plaintext query ? Because if so, in my testing, ghost returns the full html version by default, hence why i have to pass an explicitly empty array to the query.
